version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    groups:
      minor-patch:
        update-types: [minor, patch]
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      minor-patch:
        update-types: [minor, patch]
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: daily
    groups:
      minor-patch:
        update-types: [minor, patch]
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
