version: 2
multi-ecosystem-groups:
  development:
    update-types: [minor, patch]
    schedule:
      interval: daily
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
updates:
  - package-ecosystem: gomod
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: development
  - package-ecosystem: github-actions
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: development
  - package-ecosystem: uv
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: development
