name: Documentation Build

on:
  pull_request:
    paths:
      - docs/**
      - zensical.toml
      - pyproject.toml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: pyproject.toml
      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
      - name: Build documentation
        run: uv run zensical build --clean --strict
